// Generated by tools/derive_eom.py for n=1 — DO NOT EDIT BY HAND.
// Equations of motion for the inverted 1-link pendulum on a cart.
//
// Sign convention: angles theta_i measured from the upward vertical, CCW positive.
// q     = [x, theta_1, ..., theta_1]  (length 2)
// qdot  = [xdot, theta_1_dot, ..., theta_1_dot]
// params = { m0, g, cart_visc, links: [{ m, L, l, I, joint_viscous }, ...] }
//
// EOM (manipulator form):
//     M(q) * qddot + h(q, qdot) + G(q) + D(qdot) = B u
// where B = [1, 0, ..., 0]^T  (force u acts only on the cart).
//
// Solve via qddot = M^{-1} (B u - h - G - D).

export const N = 1;
export const DOF = 2;

export function M(q, qdot, params) {
  const x    = q[0];
  const xdot = qdot[0];
  const th1  = q[1];
  const thd1 = qdot[1];
  const m0 = params.m0, g = params.g, cart_visc = params.cart_visc;
  const m1 = params.links[0].m, L1 = params.links[0].L, lc1 = params.links[0].l, I1 = params.links[0].I, cv1 = params.links[0].joint_viscous;
  return [
    [m0 + m1, lc1*m1*Math.cos(th1)],
    [lc1*m1*Math.cos(th1), I1 + Math.pow(lc1, 2)*m1]
  ];
}

export function Cqdot(q, qdot, params) {
  const x    = q[0];
  const xdot = qdot[0];
  const th1  = q[1];
  const thd1 = qdot[1];
  const m0 = params.m0, g = params.g, cart_visc = params.cart_visc;
  const m1 = params.links[0].m, L1 = params.links[0].L, lc1 = params.links[0].l, I1 = params.links[0].I, cv1 = params.links[0].joint_viscous;
  return [
    -lc1*m1*Math.pow(thd1, 2)*Math.sin(th1),
    0
  ];
}

export function G(q, qdot, params) {
  const x    = q[0];
  const xdot = qdot[0];
  const th1  = q[1];
  const thd1 = qdot[1];
  const m0 = params.m0, g = params.g, cart_visc = params.cart_visc;
  const m1 = params.links[0].m, L1 = params.links[0].L, lc1 = params.links[0].l, I1 = params.links[0].I, cv1 = params.links[0].joint_viscous;
  return [
    0,
    -g*lc1*m1*Math.sin(th1)
  ];
}

export function Dqdot(q, qdot, params) {
  const x    = q[0];
  const xdot = qdot[0];
  const th1  = q[1];
  const thd1 = qdot[1];
  const m0 = params.m0, g = params.g, cart_visc = params.cart_visc;
  const m1 = params.links[0].m, L1 = params.links[0].L, lc1 = params.links[0].l, I1 = params.links[0].I, cv1 = params.links[0].joint_viscous;
  return [
    cart_visc*xdot,
    cv1*thd1
  ];
}

// Convenience: full RHS qddot = M^{-1} (B u - C - G - D).
// Pulls in a small Gaussian-elimination solver for symmetric SPD M.
export function qddot(q, qdot, u, params) {
  const Mm = M(q, qdot, params);
  const C  = Cqdot(q, qdot, params);
  const Gg = G(q, qdot, params);
  const Dd = Dqdot(q, qdot, params);
  const n = Mm.length;
  // RHS vector
  const rhs = new Array(n);
  for (let i = 0; i < n; i++) {
    rhs[i] = (i === 0 ? u : 0) - C[i] - Gg[i] - Dd[i];
  }
  return solveSPD(Mm, rhs);
}

// In-place Gaussian elimination with partial pivoting for an n x n linear solve.
// Cheap for n in {2, 3, 4}.
function solveSPD(A, b) {
  const n = A.length;
  const M2 = A.map(r => r.slice());
  const v  = b.slice();
  for (let k = 0; k < n; k++) {
    let piv = k;
    let max = Math.abs(M2[k][k]);
    for (let i = k + 1; i < n; i++) {
      const a = Math.abs(M2[i][k]);
      if (a > max) { max = a; piv = i; }
    }
    if (max < 1e-14) throw new Error("M singular");
    if (piv !== k) { [M2[k], M2[piv]] = [M2[piv], M2[k]]; [v[k], v[piv]] = [v[piv], v[k]]; }
    for (let i = k + 1; i < n; i++) {
      const f = M2[i][k] / M2[k][k];
      if (f === 0) continue;
      for (let j = k; j < n; j++) M2[i][j] -= f * M2[k][j];
      v[i] -= f * v[k];
    }
  }
  const out = new Array(n);
  for (let i = n - 1; i >= 0; i--) {
    let s = v[i];
    for (let j = i + 1; j < n; j++) s -= M2[i][j] * out[j];
    out[i] = s / M2[i][i];
  }
  return out;
}
