// tests/headless/robustness_sweep_n3.test.js — Phase 12 robustness matrix.
//
// PLAN §6.3 (Phase 12): "Robustness sweep: mass ±20%, length ±20%, friction
// ±50%, sensor noise σ ∈ {0, 0.1°, 0.5°, 1°}, delay ∈ {0, 2, 5, 10 ms}.
// Headless run per combo → success matrix written to tests/RESULTS.md."
//
// We sweep three axes (kept small so runtime is reasonable in the headless
// suite): cart_visc multiplier, mass multiplier, length multiplier. The
// criterion for "success" is closed-loop LQR brings every θ_i within 0.05
// rad of upright after 8 s sim from a 0.03 rad per-joint perturbation.
//
// Side effect: writes tests/RESULTS_robustness_n3.md alongside the canonical
// RESULTS.md so the matrix can be inspected without flooding the main file.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as eom from '../../src/physics/nlink_3.js';
import { stepRK4 } from '../../src/physics/integrator.js';
import { linearize, solveCARE } from '../../src/control/lqr.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dir = path.dirname(fileURLToPath(import.meta.url));

const baseParams = {
  m0: 1.0, g: 9.81, cart_visc: 0.05,
  links: [
    { m: 0.2,  L: 0.5, l: 0.25, I: 0.2  * 0.5 * 0.5 / 12, joint_viscous: 0.001 },
    { m: 0.15, L: 0.4, l: 0.2,  I: 0.15 * 0.4 * 0.4 / 12, joint_viscous: 0.001 },
    { m: 0.1,  L: 0.3, l: 0.15, I: 0.1  * 0.3 * 0.3 / 12, joint_viscous: 0.001 },
  ],
};

function diag(arr) {
  return Array.from({ length: arr.length }, (_, i) =>
    Array.from({ length: arr.length }, (_, j) => i === j ? arr[i] : 0));
}
function wrap(a) {
  let x = a;
  while (x > Math.PI) x -= 2 * Math.PI;
  while (x < -Math.PI) x += 2 * Math.PI;
  return x;
}
function clonePerturbed({ massMul = 1, lenMul = 1, fricMul = 1 } = {}) {
  return {
    ...baseParams,
    cart_visc: baseParams.cart_visc * fricMul,
    links: baseParams.links.map(l => ({
      m: l.m * massMul,
      L: l.L * lenMul,
      l: l.l * lenMul,
      I: l.I * massMul * lenMul * lenMul,
      joint_viscous: l.joint_viscous * fricMul,
    })),
  };
}

function tryStabilise(p) {
  // K from the TRUE (perturbed) plant — best case. Real systems would design
  // K against the nominal and let robustness margins absorb mismatch; here we
  // explicitly test the recompute-on-param-change pathway since the browser
  // controller does so.
  const { A, B } = linearize(3, p);
  const Q = diag([10, 600, 600, 600, 1, 30, 30, 30]);
  const R = 0.05;
  const { K } = solveCARE(A, B, Q, R);
  let q = [0, 0.03, 0.03, 0.03], qdot = [0, 0, 0, 0];
  const dt = 1e-4;
  const N = Math.round(8 / dt);
  const F_max = 80;
  for (let k = 0; k < N; k++) {
    const x = [q[0], wrap(q[1]), wrap(q[2]), wrap(q[3]),
               qdot[0], qdot[1], qdot[2], qdot[3]];
    let u = 0;
    for (let i = 0; i < 8; i++) u -= K[i] * x[i];
    u = Math.max(-F_max, Math.min(F_max, u));
    [q, qdot] = stepRK4(q, qdot, u, dt, p, eom);
    if (!Number.isFinite(q[1])) return { ok: false, reason: 'NaN' };
  }
  for (let i = 1; i < 4; i++) if (Math.abs(wrap(q[i])) > 0.05) return { ok: false, reason: `final θ_${i} ${wrap(q[i]).toFixed(3)}` };
  return { ok: true };
}

test('robustness sweep: nominal point succeeds', () => {
  const r = tryStabilise(clonePerturbed());
  assert.ok(r.ok, `nominal point stable (${JSON.stringify(r)})`);
});

test('robustness sweep — 27-cell matrix (mass × length × friction)', () => {
  const massMuls = [0.8, 1.0, 1.2];      // ±20%
  const lenMuls  = [0.8, 1.0, 1.2];      // ±20%
  const fricMuls = [0.5, 1.0, 1.5];      // ±50%
  const results = [];
  let passed = 0, total = 0;
  for (const mm of massMuls) {
    for (const lm of lenMuls) {
      for (const fm of fricMuls) {
        const r = tryStabilise(clonePerturbed({ massMul: mm, lenMul: lm, fricMul: fm }));
        results.push({ mass: mm, len: lm, fric: fm, ...r });
        total++;
        if (r.ok) passed++;
      }
    }
  }
  // Render as a simple markdown table grouped by friction.
  const lines = [];
  lines.push('# Phase 12 — Robustness Matrix (n=3 LQR)');
  lines.push('');
  lines.push(`Generated by tests/headless/robustness_sweep_n3.test.js — pass rate: **${passed}/${total}**.`);
  lines.push('');
  lines.push('Criterion: starting from θ_i = 0.03 rad (i=1..3), all joint angles');
  lines.push('return to within ±0.05 rad of upright after 8 s of closed-loop sim');
  lines.push('with the LQR gain recomputed for the perturbed plant.');
  lines.push('');
  for (const fm of fricMuls) {
    lines.push(`### friction × ${fm}`);
    lines.push('');
    lines.push('| mass \\ length | ' + lenMuls.map(l => `× ${l}`).join(' | ') + ' |');
    lines.push('|---|' + lenMuls.map(() => '---').join('|') + '|');
    for (const mm of massMuls) {
      const row = [`× ${mm}`];
      for (const lm of lenMuls) {
        const r = results.find(x => x.mass === mm && x.len === lm && x.fric === fm);
        row.push(r.ok ? '✅' : `❌ ${r.reason || ''}`);
      }
      lines.push('| ' + row.join(' | ') + ' |');
    }
    lines.push('');
  }
  const fp = path.resolve(__dir, '..', 'RESULTS_robustness_n3.md');
  writeFileSync(fp, lines.join('\n'));
  // Don't fail if a few cells fall over — log the rate. PLAN explicitly
  // says document the failure regime.
  console.log(`[robustness] ${passed}/${total} cells passed; matrix → ${path.basename(fp)}`);
  assert.ok(passed >= 0.7 * total, `≥ 70% of cells robust (got ${passed}/${total})`);
});
